### PR TITLE
Fix for Maximum Visible Elements

### LINKED ISSUE #11: MaximumVisibleElements
Implement set height request listview about how many items contains in the listview.
Implement displaying a count of items in the listview about the set bindable property - MaximymVisibleElements.

Please check this on iOS Platform.

### PR DESCRIPTION
**Pull request by brogowski**
Fixes #11

### CODE REVIEW

File: EntryAutoComplete/EntryAutoComplete/EntryAutoComplete/CustomControl/EntryAutoComplete.cs [hunk 1]
```diff
@@ -204,14 +211,12 @@ private void InitClearImage()
 
         private void InitSuggestionsListView()
         {
-            SuggestionsListView = new ListView
+            SuggestionsStackLayout = new StackLayout
```
Comment (krzysztofstepnikowski) [inline EntryAutoComplete/EntryAutoComplete/EntryAutoComplete/CustomControl/EntryAutoComplete.cs:214]: It's a good solution because stack layout is a container which can automatically adjust a height.
