### PR TITLE
Implement custom search property & bunch of fixes and cleanups

### LINKED ISSUE #10: Search
* Default (contains)
* Starts with
* ends with
* custom (IEqualityComparer)

### PR DESCRIPTION
**Pull request by brogowski**
Resolves #10

### CODE REVIEW

File: EntryAutoComplete/EntryAutoComplete/EntryAutoComplete/CustomControl/EntryAutoComplete.cs [hunk 1]
```diff
@@ -203,7 +216,7 @@ private void InitClearImage()
                 HorizontalOptions = LayoutOptions.End,
                 WidthRequest = 24,
                 HeightRequest = 24,
-                Margin = Device.OS!=TargetPlatform.Windows ? new Thickness(0,0,5,0) : new Thickness(0,0,10,15)
+                Margin = Device.RuntimePlatform != Device.UWP ? new Thickness(0,0,5,0) : new Thickness(0,0,10,15)
```
Comment (krzysztofstepnikowski) [inline EntryAutoComplete/EntryAutoComplete/EntryAutoComplete/CustomControl/EntryAutoComplete.cs:219]: You' re right. UWP doesn't mean like the same as Windows.

File: EntryAutoComplete/EntryAutoComplete/EntryAutoComplete/CustomControl/EntryAutoComplete.cs [hunk 2]
```diff
@@ -287,29 +306,19 @@ private void SearchEntry_TextChanged(object sender, TextChangedEventArgs e)
...
+        private void SearchEntry_IconChanged(string searchText)
         {
-            ClearSearchEntryImage.Source = string.IsNullOrEmpty(e.NewTextValue)
+            ClearSearchEntryImage.Source = string.IsNullOrEmpty(searchText)
                 ? "baseline_search_black_24.png"
                 : "baseline_close_black_24.png";
         }
 
         private IEnumerable FilterSuggestions(IEnumerable itemsSource, string searchText)
         {
```
Comment (krzysztofstepnikowski) [inline EntryAutoComplete/EntryAutoComplete/EntryAutoComplete/CustomControl/EntryAutoComplete.cs:317]: Good change. How it is simple ;)

**Review by krzysztofstepnikowski — APPROVED** [review]
Thank you so much. Good job @brogowski
